### PR TITLE
Force installation on source change

### LINKED ISSUE #35: Reset "lib"-dir during local testing
When testing locally using `run_script` touchstone will skip installing the package if it is already installed in the dir matching the current `ref`, which is good in case there are just changes to `script.R` but is a bit annoying when changing the package itself and using branch names as refs .

It would be nice if touchstone checked the actual commit sha or something, of the installed package version instead of just the branch name.  Maybe this functionality already exists and I just haven't turned it on ^-^.

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #35.

### CODE REVIEW

**Comment by assignUser** [comment]
This is exactly what I was looking for in #35  but does not work as intended (on Windows) as checking out branches updates the modification date on files that differ between the branches to the time of the branch change.

image

image

**Comment by assignUser** [comment]
Maybe changedFiles is an option for `last_source_change`? 
https://stat.ethz.ch/R-manual/R-devel/library/utils/html/changedFiles.html

I'll check it out later!

**Comment by lorenzwalthert** [comment]
You are right of course 😫 I found a better way than my first approach. Using `md5` checksums, we should be able to detect changes in the file contents reliably, per ref and package root. The `changedFiles` was the hint to `tools::md5sum()`, so thanks for this. The `changedFiles()` API looked a bit convoluted to me, so I felt I prefer to implement it myself.

**Comment by lorenzwalthert** [comment]
@assignUser can you try again? 😄

**Comment by assignUser** [comment]
@lorenzwalthert Awesome! That works perfectly! 🎉

**Comment by lorenzwalthert** [comment]
Ok, glad it works now 👍

**Pull request merged**
