### PR TITLE
expr_eval should handle character expressions with length > 1

### PR DESCRIPTION
**Pull request by lorenzwalthert**
@assignUser, #38 actually [broke code](https://github.com/r-lib/styler/pull/835) in {styler}. An unexpected case but fixed it (hopefully).

### CODE REVIEW

**Comment by assignUser** [comment]
I disagree with the title for these reasons:
 * API: allowing character vectors length >1 is inconsistent with the API for the benchmarking argument which is specified as only length one. We should actually extend the test in https://github.com/lorenzwalthert/touchstone/blob/432dc1eca810ff398130ceb0e74b0bd92f455b7e/R/core.R#L81-L82 to `expr_before_benchmark`
 * Consistency: We allow for passing expressions as strings OR expressions `c("library(styler)","func()") ` does **both**. Imo it should be  either `"library(styler); func()"`or `{library(styler); func()}` 
 * Feasibility: We would need to create a check specifically for this situation, check if it is a call, check that the function is `c`, evaluate once, parse, evaluate again. If we just evaluate all calls what happens to functions passed normally that may or may not return a string? 

Overall I think it makes more sense to change the code in styler and reinforce the API by adding a check.

Or allow character vectors length > 1 for both `expr_before_benchmark` and `...` and add specific handling for that situation. This is imo not worth the effort and possible issues down the line, as I would guess most new users of touchstone will  use expressions/tidy eval instead of passing strings.

But in the end it is your package ;)

**Comment by lorenzwalthert** [comment]
I agree it's a bad idea in particular because of consistency and I realized I broke some other cases (glad we have tests :D). I think since [adaption](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/r.py#L18) is pretty limited still, we should maybe not allow strings at all anymore?

**Comment by assignUser** [comment]
I don't think that link is the one you wanted to put there... or I don't under stand 😁 
Yes tests save my a** all the time xD

I think it makes sense to only use expressions, I will let you decide though :P

**Comment by lorenzwalthert** [comment]
That's the link that tells you how many GitHub projects use {touchstone}: https://github.com/search?q=path%3A.github%2Fworkflows+filename%3Atouchstone-receive.yaml&type=Code

**Comment by assignUser** [comment]
No it's a link to `r.py` in precommit^^ But the new link works, it does not search in forks it seems as I am using it in a fork of our package for testing, But yeah looks like the time for breaking changes is now 😄

**Pull request closed without merging**
