### PR TITLE
Bump action version

### PR DESCRIPTION
**Pull request by assignUser**
I created a v1 tag and added it to the `.yaml`s so people testing can use a stable version and not be disrupted

### CODE REVIEW

**Review by lorenzwalthert — APPROVED** [review]
Good idea

**Review by lorenzwalthert — APPROVED** [review]
can you actually also update the README in `actions/`?

**Review by lorenzwalthert — COMMENTED** [review]
can you adapt the `README.md` in `actions/`?

**Review by lorenzwalthert — CHANGES_REQUESTED** [review]
can you adapt the `README.md` in `actions/`?

**Comment by assignUser** [comment]
@lorenzwalthert What do you think, is that enough? Also precommit thought I needed to render that :D

**Review by lorenzwalthert — APPROVED** [review]
Good. Apart from the fact that we could have chosen a version < 1, and then 1.0.0 for the CRAN release.

**Pull request merged**
