### PR TITLE
API overhaul

### LINKED ISSUE #77: API Review
* API review, i.e. 
  * `benchmark_run_ref()` should probably be called `benchmark_run()` only.
  * Not sure we should continue to use the notion *ref(s)*. Because it might be misleading, since the refs are mostly branches (i.e. heads), not arbitrary commits on a branch. Also, you can create a branch from an arbitrary commit and benchmark it, so for people who are not git geeks, using *branch* might make more sense than *ref*. This affects exported function names and arguments and documentation. 

_Originally posted by @lorenzwalthert in https://github.com/lorenzwalthert/touchstone/issues/31#issuecomment-962508956_

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #77. Please see file [`API`](https://github.com/lorenzwalthert/touchstone/pull/83/files#diff-c8e5998f6a3955c21d858936fe05c69621724d7f825c6e17793002a0fa798bf9) for how the new API looks like.

### CODE REVIEW

**Review by assignUser — APPROVED** [review]
I have tested the changes locally and everything works fine!

**Comment by lorenzwalthert** [comment]
That's great. Can you have a look at [API](https://github.com/lorenzwalthert/touchstone/pull/83/files#diff-c8e5998f6a3955c21d858936fe05c69621724d7f825c6e17793002a0fa798bf9) and tell me whether you think the changes make sense? One thing I was not sure about is plural / singular. E.g. `benchmarks_analyse()` because you can supply multiple branches (same with `branches_install()`), but `benchmark_read()` because you can only supply one branch.

**Comment by assignUser** [comment]
I think `benchmarkS_analyse` is good but I think it should be `branch_install` because it could be used to install only one branch too right? And I think it reads better for some reason xD but that's not a strong opinion if you feel that plural is better in this case (as it is the most common use case) I would also be ok with that. Otherwise I think the API now looks sensible! 

p.s. sorry for the late reply

**Comment by lorenzwalthert** [comment]
I think we should make it all singular now :D. Plus we should probably get rid of the `path_pkg` argument, because 1) it won't be hardly used plus 2) we either use it in the whole API or not at all.

**Pull request merged**
