### PR TITLE
Closing multiple small issues 

### LINKED ISSUE #46: New contributor
@assignUser thanks so much for your recent work on {touchstone}. I'd like to make you a contributor (called author in the CRAN slang) to the package if you want. We'd have to change the following field in `DESCRIPTION`: `person()` -> `c(person(...), person(...))`

```r
Authors@R: 
    person(given = "Lorenz",
           family = "Walthert",
           role = c("aut", "cre"),
           email = "lorenz.walthert@icloud.com")
```

You can file a PR if interested.

### LINKED ISSUE #47: wording: script.R
I think we should adopt this in various documentation places: 
* `touchstone_script` (with helpfile link) instead of `script.R`.
* setting `'touchstone/script.R'` as the default script path for `touchstone::run_script()`.

### LINKED ISSUE #48: Imports/Suggests
@lorenzwalthert  I just noticed that you list dplyr, withr, glue , ggplot2 ... in suggests only, should they not be listed as imports?  At least dplyr and ggplot2 as we don't have anything else afaik that depends on it compared to glue etc.

### PR DESCRIPTION
**Pull request by assignUser**
Closes #46 Thank you, I appreciate it! 

Closes #47  This was a quick fix.

Closes #48  Discard these changes if you don't think this is necessary.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks. See my comments in #48. Also, what's the advantage of {openssl} or {digest}?

**Comment by assignUser** [comment]
{openssl} is free with {gert} :D

I implemented the changes we talked about in #48

**Review by lorenzwalthert — APPROVED** [review]
You can import the free packages and use cli instead of usethis.

**Comment by lorenzwalthert** [comment]
Let me know when you’re ready, and I will merge.

**Comment by assignUser** [comment]
So I looked into replacing {usethis} and {cli} is not a simple drop-in replacement as I thought but would require us to reimplement some functions and I do not think the effort to re-implement and maintain those function would be worth the slight speed up during install it.

So I would say go ahead and merge :)

**Pull request merged**
