### PR TITLE
allow specifying extra packages

### LINKED ISSUE #128: Allow install of extra packages
The touchstone setup might require extra packages that aren't installed as part of the `setup-r-dependencies` action (e.g. avoiding remotes in order to be cran compliant). It might be good to allow specification of extra packages to install for touchstone.

### PR DESCRIPTION
**Pull request by sbfnk**
Closes #128

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks for the contribution. I can’t check if that works. Did you try it with a fork already?

**Comment by sbfnk** [comment]
I tried it successfully in https://github.com/epiforecasts/EpiNow2/pull/551 (see also [workflow file](https://github.com/epiforecasts/EpiNow2/blob/9cba885f542d0c64a88252d16bf029610ff0481d/.github/workflows/touchstone-receive.yaml#L54) and [action log](https://github.com/epiforecasts/EpiNow2/actions/runs/7907683405))

**Comment by lorenzwalthert** [comment]
ok, thanks.

**Review by assignUser — COMMENTED** [review]
Nice!

**Pull request merged**
