### PR TITLE
fix unbalanced backtick

### PR DESCRIPTION
**Pull request by Moohan**

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks @Moohan. I fixed it already but have not merged it, so I give you the commit :D

**Comment by lorenzwalthert** [comment]
If you want, fix it in `README.Rmd` too, because the `.md` is a derivative and we don't edit it manually.

**Comment by Moohan** [comment]
Think that should be it. I didn't check out the code and build the .md... I just edited them both in GitHub. 

Have you seen this workflow example: https://github.com/r-lib/actions/tree/master/examples#render-rmarkdown which can be modified/implemented to re-build the .md file on push/pull etc.

**Comment by lorenzwalthert** [comment]
Thanks again

**Pull request merged**
