### PR TITLE
Drop support for character input

### LINKED ISSUE #61: Hard deprecate the use of strings in inputs
This is very confusing, because in general, a character vector of length one is identical to a string. Not in our case:

``` r
f <- function(...) {
  dots <- rlang::enexprs(...)
  print(dots)
}

f("x")
#> [[1]]
#> [1] "x"
f(c("x"))
#> [[1]]
#> c("x")
```

<sup>Created on 2021-09-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This made https://github.com/lorenzwalthert/touchstone.test/pull/4 fail. @assignUser any objections?

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #61.

### CODE REVIEW

**Comment by assignUser** [comment]
This would also allow us to simplify `expres_eval` or even switch to quosures after all, which would streamline the usage of variables   that are defined within `script.R `, I could have a look at that if you are interested, might be a few days I'm still a bit swamped with irl stuff :)

**Comment by lorenzwalthert** [comment]
Is this ready to merge?

**Comment by assignUser** [comment]
@lorenzwalthert I would say now it is :) 
I completely removed `exprs_eval` as we don't need it when we can guarantee that we only get expressions.
I have played around with quosures but that caused inconsistencies in the environment between benchmarks and overall was not really an advantage and increased complexity for us and the user, so I dropped that idea.

**Comment by lorenzwalthert** [comment]
Thanks @assignUser.

**Pull request merged**
