### PR TITLE
Add process overview to starter vignette

### LINKED ISSUE #79: Workflow documentation
@assignUser what do you think of this (detail suggestions also welcome)? I think we could create a vignette and add some paragraph.

Screenshot 2021-11-20 at 12 18 09

As pdf: [workflow-visualization.pdf](https://github.com/lorenzwalthert/touchstone/files/7574444/workflow-visualization.pdf)

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #79.

### CODE REVIEW

**Review by assignUser — APPROVED** [review]
Looks good, you decided to keep the inital version of the visualization?

**Comment by lorenzwalthert** [comment]
I have, sorry, (force) pushed again. Should have used draw.io or something else than Apple pages to generate it though. The source file is too big to commit (0.2MB) and pdf is binary -.-

**Comment by lorenzwalthert** [comment]
I pushed the raw data to the cloud too: https://github.com/lorenzwalthert/some_raw_data/blob/master/touchstone-workflow-visualization.pages

**Comment by assignUser** [comment]
I have converted the pages file to `.odt` and checked that everything converted correctly. it is just 24kB.  I have attached it here because I was unsure where to put it in the repo :D 
[touchstone-workflow-visualization.odt](https://github.com/lorenzwalthert/touchstone/files/7598750/touchstone-workflow-visualization.odt)

**Comment by lorenzwalthert** [comment]
Great, I added it to the repo in `inst/`, where the PDF resides.

**Pull request merged**
