### PR TITLE
Make pr comment customizable

### LINKED ISSUE #56: Configurable header/footer
I think it would be nice to be able to modify the header/footer of the PR comment, e.g. with steps to take for contributors if times are worse. Maybe even conditional footer with {praise} when non are sig. worse? :D

Definitely low priority though.

### PR DESCRIPTION
**Pull request by assignUser**
This should work but needs some more documentation and I want to test it on a real PR.
But you can have a look @lorenzwalthert and let me know what you think :)

Closes #56

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Ok. You can also test here: 

https://github.com/lorenzwalthert/touchstone.test

This package has a function called `install_use_push()` that takes a branch ref from {touchstone}, installs it, relaxes the GitHub action templates and commits + pushes the changes. Then you can open a PR and see how it looks.

**Comment by assignUser** [comment]
thats cool but due to it using `sed` it does not work on windows... maybe it is time to at least dual boot again :D

**Comment by assignUser** [comment]
Tested it and added documentation.
image

**Comment by lorenzwalthert** [comment]
Thanks

**Pull request merged**
